version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: pg
    ports:
      - 5439:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'root']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

  jaeger:
    image: jaegertracing/all-in-one
    environment:
      COLLECTOR_OTLP_ENABLED: true
    ports:
      # - 6831:6831/udp
      # - 6832:6832/udp
      # - 5778:5778
      - 5113:16686
      # - 4317:4317
      - 4418:4318
      - 14251:14250
      # - 14268:14268
      # - 14269:14269
      # - 9411:9411

volumes:
  postgres:
