# Configuration file for Rustfmt
# https://rust-lang.github.io/rustfmt

edition = "2021"

# Basic
hard_tabs = true
max_width = 100

# Consistency
newline_style = "Unix"

# Misc
chain_width = 80
match_block_trailing_comma = true
